### ISSUE TITLE
issuesSHARK plugin in serverSHARK error

### ISSUE THREAD

**Issue by iwonajs** [smartshark/serverSHARK#40]
1. created new VM
2. using serverSHARK add first and only plugin: issuesSHARK
3. using serverSHARK crate first and only project: 'zookeeper'
4. using serverSHARK start collecting data for project zookeeper
Arguments: 
Same as in the issuesSHARK tutorial
https://github.com/smartshark/issueSHARK
![image](https://user-images.githubusercontent.com/32595047/89111208-f0aaf880-d420-11ea-9107-2016e1a7dea7.png)

5. Error:
Error was not logged in any of the logging files.
Provided screenshot instead.
![image](https://user-images.githubusercontent.com/32595047/89110902-aecc8300-d41d-11ea-8fd4-dd61e9f9a7b9.png)
![image](https://user-images.githubusercontent.com/32595047/89110975-7ed1af80-d41e-11ea-838d-ed0ade119120.png)
![image](https://user-images.githubusercontent.com/32595047/89110980-8a24db00-d41e-11ea-910b-fd1a8e3ebb31.png)
![image](https://user-images.githubusercontent.com/32595047/89110983-93ae4300-d41e-11ea-9799-0b58b045fc15.png)

6. Note: In a sperate VM, I downloaded the commits for my project of interest 'spring-boot', I had some issues with extracting issues from github. So I tested the issues plugin by creating new project 'zookeeper' and using the configs form the tutorial I was able to download just above 4,000 issues. However I could not get it to work for 'spring-boot' on github. I created a new project and tried to download issues using new projects. I could not get that to work.
But few days ago, I installed the issuesSHARK plugin in on the command line (on a separate VM) and it worked! I did not confirm if all the issues I expected downloaded though.

Thank you.

**Comment by atrautsch** [comment]
Thank you for your bug report.
The error looks like the credentials are wrong. Can you login with these credentials (issue_user, issue_password) on the jira.apache.org site? There could also be some kind of rate limiting on the Jira. If the credentials are valid maybe wait a day or two before downloading new issues.

Regarding the github issues, did you include a github token instead of issue_user, issue_password?
It is probably not clear from the documentation but to read the issues via the github AP issueSHARK needs this token to authenticate your user.

**Comment by iwonajs** [comment]
For github issues I did use a token.
When I was crating the token I did not check any privileges.
Now I created a new github token and this time check all permissions.
Here is the log output:
![image](https://user-images.githubusercontent.com/32595047/89568866-ea869480-d7f1-11ea-8892-a96ce579754f.png)
Here are the configs for the job:
![image](https://user-images.githubusercontent.com/32595047/89569273-7698bc00-d7f2-11ea-8b12-90da0447e073.png)

The issue repository open source project. 
The issues are public. I am assuming I should have privileges to download the issues via api.

**Comment by iwonajs** [comment]
My bad!
For GitHub I was using:
https://github.com/spring-projects/spring-boot/issues
But I need the api url version:
https://api.github.com/repos/spring-projects/spring-boot/issues

That is working!
If it stops, then I will assume its out of memory. I will then just restart the server.
Thank you!
