### ISSUE TITLE
How to stop massive jobs

### ISSUE THREAD

**Issue by yiikou** [smartshark/serverSHARK#41]
Cannot stop jobs (even after setting all of them as exit) and I did a stupid operation `vagrant reload`, try to clear the job queue. But the result is: 1) jobs are still in the queue. 2) but all of them cannot be executed due to the missing data in /tmp. The result is that I successfully stop 2k+ jobs, but also get tons of logs.
Here is the log 
```
rsync: change_dir "/tmp/servershark/projects/junit4" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

So, how to stop jobs properly?

Thank you.

**Comment by yiikou** [comment]
Just realize that I cannot change project information after reloading vagrant. It shows DuplicateKeyError:
```

Request Method: | POST
-- | --
http://127.0.0.1:8001/admin/smartshark/project/2/change/
1.11.29
DuplicateKeyError
E11000 duplicate key error collection: smartshark.project index: name_1 dup key: { : "junit4" }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: smartshark.project index: name_1 dup key: { : "junit4" }'}
/srv/www/serverSHARK/lib/python3.6/site-packages/pymongo/helpers.py in _raise_last_write_error, line 211
/srv/www/serverSHARK/bin/python
3.6.9
['/srv/www/serverSHARK/smartshark/datacollection',  '/srv/www/serverSHARK/smartshark/datacollection'
......
......

'/srv/www/serverSHARK/smartshark/datacollection',  '/srv/www/serverSHARK',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/srv/www/serverSHARK/lib/python3.6/site-packages',  '/var/www/servershark']
```

**Comment by atrautsch** [comment]
Currently, jobs can not be stopped from the GUI in Vagrant, that functionality is only supported for a HPC deployment.
You can clear the redis queue which holds the jobs with redis-cli flushall

For the DuplicateKeyError, it is not possible to rename projects from the GUI.

**Comment by sherbold** [comment]
See #21 for renaming - long planned but never implemented feature, because this is surprisingly ugly with MongoDB.

**Comment by yiikou** [comment]
Hi @sherbold, I have a problem related to project name when using refShark (https://github.com/smartshark/refSHARK/issues/3). Do you think that problem is related to this one?
